name: tadkir
base: core22
version: '1.0.1'
summary: Periodic Thikr notifications (تطبيق تذكير)
description: |
  Tadkir is a simple utility that sends periodic desktop notifications 
  to remind the user of Tasbih and Thikr. 
  برنامج بسيط لإرسال تنبيهات دورية بالأذكار.
license: CC-BY-NC-4.0

grade: stable
confinement: strict

parts:
  tadkir:
    plugin: nil
    source: .
    build-packages:
      - g++
      - libnotify-dev
      - libglib2.0-dev
      - pkg-config
    stage-packages:
      - libnotify4
      - libglib2.0-0
    override-build: |
      g++ main.cpp -o tadkir $(pkg-config --cflags --libs libnotify)
      install -D tadkir $SNAPCRAFT_PART_INSTALL/bin/tadkir

apps:
  tadkir:
    command: bin/tadkir
    # This ensures the app can talk to the notification system properly
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
